# .github/workflows/playwright.yml
name: Playwright Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Build Next.js app
        run: npm run build
      - name: Run Playwright tests
        run: npm run test:e2e